[package]
name = "qr-gen-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = "0.9.0-beta.1"
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
log = "0.4.17"

qrcodegen = "1.8.0"